TRAINING_DATA = [
    # Examples for BATSMAN
    ("Virat Kohli hit 6 runs off the last ball", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Rohit Sharma hit a boundary", {"entities": [(0, 12, "BATSMAN")]}),
    ("MS Dhoni finished the match with a six", {"entities": [(0, 7, "BATSMAN")]}),
    ("David Warner scored a century", {"entities": [(0, 12, "BATSMAN")]}),
    ("Joe Root played a fine innings", {"entities": [(0, 8, "BATSMAN")]}),
    ("Steven Smith hit 4 fours in an over", {"entities": [(0, 12, "BATSMAN")]}),
    ("Kane Williamson anchored the innings", {"entities": [(0, 15, "BATSMAN")]}),
    ("Chris Gayle blasted the ball for a six", {"entities": [(0, 11, "BATSMAN")]}),
    ("Babar Azam steadied the chase", {"entities": [(0, 10, "BATSMAN")]}),
    ("Faf du Plessis was aggressive", {"entities": [(0, 13, "BATSMAN")]}),
    ("Quinton de Kock hit consecutive boundaries", {"entities": [(0, 15, "BATSMAN")]}),
    ("Shikhar Dhawan was dismissed early", {"entities": [(0, 14, "BATSMAN")]}),
    ("Ajinkya Rahane led the team", {"entities": [(0, 13, "BATSMAN")]}),
    ("Rishabh Pant played a scoop shot", {"entities": [(0, 11, "BATSMAN")]}),
    ("KL Rahul played a vital role", {"entities": [(0, 7, "BATSMAN")]}),
    ("Shreyas Iyer rotated the strike well", {"entities": [(0, 12, "BATSMAN")]}),
    ("Dinesh Karthik finished the match", {"entities": [(0, 14, "BATSMAN")]}),
    ("Hardik Pandya hit the winning runs", {"entities": [(0, 12, "BATSMAN")]}),
    ("Suryakumar Yadav was explosive", {"entities": [(0, 15, "BATSMAN")]}),
    ("Prithvi Shaw made a quickfire 30", {"entities": [(0, 11, "BATSMAN")]}),
    ("Shubman Gill displayed maturity", {"entities": [(0, 11, "BATSMAN")]}),
    ("Manish Pandey supported the innings", {"entities": [(0, 12, "BATSMAN")]}),
    ("Sanju Samson played aggressively", {"entities": [(0, 11, "BATSMAN")]}),
    ("Mayank Agarwal scored a half-century", {"entities": [(0, 14, "BATSMAN")]}),
    ("Kedar Jadhav hit a crucial boundary", {"entities": [(0, 11, "BATSMAN")]}),
    ("Ishan Kishan hit a quickfire 50", {"entities": [(0, 11, "BATSMAN")]}),
    ("Ambati Rayudu was solid", {"entities": [(0, 12, "BATSMAN")]}),
    ("Ravindra Jadeja finished the game", {"entities": [(0, 15, "BATSMAN")]}),
    ("Axar Patel hit a winning six", {"entities": [(0, 10, "BATSMAN")]}),
    ("Ravichandran Ashwin hit a boundary", {"entities": [(0, 20, "BATSMAN")]}),
    ("Shardul Thakur played the finisher's role", {"entities": [(0, 13, "BATSMAN")]}),
    ("Washington Sundar was excellent", {"entities": [(0, 18, "BATSMAN")]}),
    ("Harbhajan Singh scored valuable runs", {"entities": [(0, 16, "BATSMAN")]}),
    ("Yuzvendra Chahal hit the winning runs", {"entities": [(0, 16, "BATSMAN")]}),
    ("Kuldeep Yadav scored a boundary", {"entities": [(0, 13, "BATSMAN")]}),
    ("Jasprit Bumrah hit the winning runs", {"entities": [(0, 14, "BATSMAN")]}),
    ("Mohammed Shami was resilient", {"entities": [(0, 15, "BATSMAN")]}),
    ("Umesh Yadav hit a six", {"entities": [(0, 11, "BATSMAN")]}),
    ("Bhuvneshwar Kumar batted well", {"entities": [(0, 17, "BATSMAN")]}),
    ("Navdeep Saini hit a four", {"entities": [(0, 13, "BATSMAN")]}),
    ("Deepak Chahar was calm under pressure", {"entities": [(0, 13, "BATSMAN")]}),
    ("T Natarajan hit the last ball for a four", {"entities": [(0, 11, "BATSMAN")]}),
    ("Shane Watson smashed the ball", {"entities": [(0, 12, "BATSMAN")]}),
    ("Sam Curran played a crucial role", {"entities": [(0, 9, "BATSMAN")]}),
    ("Tom Banton hit a massive six", {"entities": [(0, 10, "BATSMAN")]}),
    ("Jason Roy hit the winning runs", {"entities": [(0, 9, "BATSMAN")]}),
    ("Eoin Morgan played a captain's knock", {"entities": [(0, 11, "BATSMAN")]}),
    ("Jos Buttler was dismissed early", {"entities": [(0, 10, "BATSMAN")]}),
    ("Ben Stokes hit the winning boundary", {"entities": [(0, 9, "BATSMAN")]}),
    ("Jonny Bairstow played aggressively", {"entities": [(0, 13, "BATSMAN")]}),
    ("Moeen Ali scored a boundary", {"entities": [(0, 8, "BATSMAN")]}),
    
    # Examples for BOWLER
    ("Jasprit Bumrah bowled a dot ball", {"entities": [(0, 14, "BOWLER"), (22, 30, "DELIVERY")]}),
    ("Ravichandran Ashwin bowled a maiden over", {"entities": [(0, 20, "BOWLER")]}),
    ("Mitchell Starc was on fire with the ball", {"entities": [(0, 14, "BOWLER")]}),
    ("Trent Boult bowled a hat-trick", {"entities": [(0, 11, "BOWLER")]}),
    ("Pat Cummins bowled with great pace", {"entities": [(0, 11, "BOWLER")]}),
    ("Bhuvneshwar Kumar bowled economically", {"entities": [(0, 17, "BOWLER")]}),
    ("Kagiso Rabada bowled a fast over", {"entities": [(0, 12, "BOWLER")]}),
    ("Anrich Nortje bowled at high speeds", {"entities": [(0, 12, "BOWLER")]}),
    ("Chris Morris bowled the last over", {"entities": [(0, 11, "BOWLER")]}),
    ("Lungi Ngidi bowled a crucial over", {"entities": [(0, 11, "BOWLER")]}),
    ("Imran Tahir took a crucial wicket", {"entities": [(0, 11, "BOWLER")]}),
    ("Yuzvendra Chahal bowled brilliantly", {"entities": [(0, 16, "BOWLER")]}),
    ("Kuldeep Yadav took two wickets", {"entities": [(0, 13, "BOWLER")]}),
    ("Adil Rashid bowled a tight spell", {"entities": [(0, 11, "BOWLER")]}),
    ("Rashid Khan bowled with precision", {"entities": [(0, 11, "BOWLER")]}),
    ("Shakib Al Hasan bowled well", {"entities": [(0, 15, "BOWLER")]}),
    ("Sunil Narine bowled economically", {"entities": [(0, 12, "BOWLER")]}),
    ("Mustafizur Rahman bowled a yorker", {"entities": [(0, 17, "BOWLER")]}),
    ("Jofra Archer bowled the fastest ball", {"entities": [(0, 11, "BOWLER")]}),
    ("James Anderson bowled with swing", {"entities": [(0, 15, "BOWLER")]}),
    ("Stuart Broad bowled a bouncer", {"entities": [(0, 12, "BOWLER")]}),
    ("Mark Wood bowled with aggression", {"entities": [(0, 9, "BOWLER")]}),
    ("Nathan Lyon bowled a good length", {"entities": [(0, 11, "BOWLER")]}),
    ("Josh Hazlewood bowled accurately", {"entities": [(0, 14, "BOWLER")]}),
    ("Pat Cummins bowled a perfect line", {"entities": [(0, 11, "BOWLER")]}),
    ("Mitchell Johnson bowled fiercely", {"entities": [(0, 16, "BOWLER")]}),
    ("Glenn McGrath bowled consistently", {"entities": [(0, 12, "BOWLER")]}),
    ("Shane Warne bowled a leg break", {"entities": [(0, 11, "BOWLER")]}),
    ("Muttiah Muralitharan bowled a doosra", {"entities": [(0, 21, "BOWLER")]}),
    ("Lasith Malinga bowled a slower ball", {"entities": [(0, 14, "BOWLER")]}),
    ("Dale Steyn bowled with pace", {"entities": [(0, 10, "BOWLER")]}),
    ("Shaun Pollock bowled a tight line", {"entities": [(0, 13, "BOWLER")]}),
    ("Allan Donald bowled with aggression", {"entities": [(0, 12, "BOWLER")]}),
    ("Courtney Walsh bowled a bouncer", {"entities": [(0, 14, "BOWLER")]}),
    ("Curtly Ambrose bowled with hostility", {"entities": [(0, 13, "BOWLER")]}),
    ("Wasim Akram bowled a reverse swing", {"entities": [(0, 11, "BOWLER")]}),
    ("Waqar Younis bowled a toe-crusher", {"entities": [(0, 12, "BOWLER")]}),
    ("Anil Kumble bowled a flipper", {"entities": [(0, 11, "BOWLER")]}),
    ("Shoaib Akhtar bowled at lightning speed", {"entities": [(0, 13, "BOWLER")]}),
    ("Saqlain Mushtaq bowled a doosra", {"entities": [(0, 15, "BOWLER")]}),
    ("Harbhajan Singh bowled a doosra", {"entities": [(0, 16, "BOWLER")]}),
    ("Zaheer Khan bowled a yorker", {"entities": [(0, 11, "BOWLER")]}),
    ("Jasprit Bumrah bowled a slower ball", {"entities": [(0, 14, "BOWLER")]}),
    ("Mohammed Shami bowled a good length", {"entities": [(0, 15, "BOWLER")]}),
    ("Ishant Sharma bowled with control", {"entities": [(0, 12, "BOWLER")]}),
    ("Umesh Yadav bowled a sharp bouncer", {"entities": [(0, 11, "BOWLER")]}),
    ("Navdeep Saini bowled a short ball", {"entities": [(0, 13, "BOWLER")]}),
    ("Bhuvneshwar Kumar bowled the last over", {"entities": [(0, 17, "BOWLER")]}),
    ("Deepak Chahar bowled accurately", {"entities": [(0, 13, "BOWLER")]}),
    ("T Natarajan bowled the perfect yorker", {"entities": [(0, 11, "BOWLER")]}),

    # Examples for RUNS
    ("Virat Kohli hit 4 runs", {"entities": [(0, 11, "BATSMAN"), (16, 17, "RUNS")]}),
    ("Rohit Sharma scored 50 runs", {"entities": [(0, 12, "BATSMAN"), (21, 22, "RUNS")]}),
    ("MS Dhoni took a single", {"entities": [(0, 7, "BATSMAN"), (15, 21, "RUNS")]}),
    ("David Warner smashed 6 runs", {"entities": [(0, 12, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Joe Root accumulated 3 runs", {"entities": [(0, 8, "BATSMAN"), (22, 23, "RUNS")]}),
    ("Steven Smith scored 2 runs", {"entities": [(0, 12, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Kane Williamson scored 75 runs", {"entities": [(0, 15, "BATSMAN"), (23, 24, "RUNS")]}),
    ("Chris Gayle hit 8 runs", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Babar Azam made 90 runs", {"entities": [(0, 10, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Faf du Plessis scored 100 runs", {"entities": [(0, 13, "BATSMAN"), (21, 22, "RUNS")]}),
    ("Quinton de Kock scored 5 runs", {"entities": [(0, 15, "BATSMAN"), (23, 24, "RUNS")]}),
    ("Shikhar Dhawan hit 7 runs", {"entities": [(0, 14, "BATSMAN"), (18, 19, "RUNS")]}),
    ("Ajinkya Rahane hit 3 runs", {"entities": [(0, 13, "BATSMAN"), (17, 18, "RUNS")]}),
    ("Rishabh Pant hit 9 runs", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("KL Rahul scored 1 run", {"entities": [(0, 7, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Shreyas Iyer accumulated 65 runs", {"entities": [(0, 12, "BATSMAN"), (23, 24, "RUNS")]}),
    ("Dinesh Karthik hit 80 runs", {"entities": [(0, 14, "BATSMAN"), (18, 19, "RUNS")]}),
    ("Hardik Pandya hit 12 runs", {"entities": [(0, 12, "BATSMAN"), (16, 17, "RUNS")]}),
    ("Suryakumar Yadav scored 110 runs", {"entities": [(0, 15, "BATSMAN"), (24, 25, "RUNS")]}),
    ("Prithvi Shaw scored 22 runs", {"entities": [(0, 11, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Shubman Gill made 33 runs", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Manish Pandey accumulated 44 runs", {"entities": [(0, 12, "BATSMAN"), (23, 24, "RUNS")]}),
    ("Sanju Samson hit 55 runs", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Mayank Agarwal scored 66 runs", {"entities": [(0, 14, "BATSMAN"), (22, 23, "RUNS")]}),
    ("Kedar Jadhav made 77 runs", {"entities": [(0, 11, "BATSMAN"), (16, 17, "RUNS")]}),
    ("Ishan Kishan hit 88 runs", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Ambati Rayudu scored 99 runs", {"entities": [(0, 12, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Ravindra Jadeja made 20 runs", {"entities": [(0, 15, "BATSMAN"), (19, 20, "RUNS")]}),
    ("Axar Patel hit 30 runs", {"entities": [(0, 10, "BATSMAN"), (14, 15, "RUNS")]}),
    ("Ravichandran Ashwin hit 40 runs", {"entities": [(0, 20, "BATSMAN"), (24, 25, "RUNS")]}),
    ("Shardul Thakur scored 50 runs", {"entities": [(0, 13, "BATSMAN"), (21, 22, "RUNS")]}),
    ("Washington Sundar made 60 runs", {"entities": [(0, 18, "BATSMAN"), (22, 23, "RUNS")]}),
    ("Harbhajan Singh hit 70 runs", {"entities": [(0, 16, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Yuzvendra Chahal made 80 runs", {"entities": [(0, 16, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Kuldeep Yadav scored 90 runs", {"entities": [(0, 13, "BATSMAN"), (21, 22, "RUNS")]}),
    ("Jasprit Bumrah hit 100 runs", {"entities": [(0, 14, "BATSMAN"), (18, 19, "RUNS")]}),
    ("Mohammed Shami made 150 runs", {"entities": [(0, 15, "BATSMAN"), (19, 20, "RUNS")]}),
    ("Umesh Yadav scored 200 runs", {"entities": [(0, 11, "BATSMAN"), (19, 20, "RUNS")]}),
    ("Bhuvneshwar Kumar hit 250 runs", {"entities": [(0, 17, "BATSMAN"), (21, 22, "RUNS")]}),
    ("Navdeep Saini made 300 runs", {"entities": [(0, 13, "BATSMAN"), (17, 18, "RUNS")]}),
    ("Deepak Chahar scored 350 runs", {"entities": [(0, 13, "BATSMAN"), (21, 22, "RUNS")]}),
    ("T Natarajan hit 400 runs", {"entities": [(0, 11, "BATSMAN"), (15, 16, "RUNS")]}),
    ("Shane Watson scored 450 runs", {"entities": [(0, 12, "BATSMAN"), (20, 21, "RUNS")]}),
    ("Sam Curran made 500 runs", {"entities": [(0, 9, "BATSMAN"), (14, 15, "RUNS")]}),
    ("Tom Banton hit 550 runs", {"entities": [(0, 10, "BATSMAN"), (14, 15, "RUNS")]}),
    ("Jason Roy made 600 runs", {"entities": [(0, 9, "BATSMAN"), (13, 14, "RUNS")]}),
    ("Eoin Morgan scored 650 runs", {"entities": [(0, 11, "BATSMAN"), (19, 20, "RUNS")]}),
    ("Jos Buttler made 700 runs", {"entities": [(0, 10, "BATSMAN"), (14, 15, "RUNS")]}),
    ("Ben Stokes hit 750 runs", {"entities": [(0, 9, "BATSMAN"), (13, 14, "RUNS")]}),
    ("Jonny Bairstow scored 800 runs", {"entities": [(0, 13, "BATSMAN"), (21, 22, "RUNS")]}),
    ("Moeen Ali made 850 runs", {"entities": [(0, 8, "BATSMAN"), (12, 13, "RUNS")]}),

    # Examples for DELIVERY
    ("Jasprit Bumrah bowled a yorker", {"entities": [(0, 14, "BOWLER"), (22, 28, "DELIVERY")]}),
    ("Ravichandran Ashwin bowled a bouncer", {"entities": [(0, 20, "BOWLER"), (28, 35, "DELIVERY")]}),
    ("Mitchell Starc bowled a slower ball", {"entities": [(0, 14, "BOWLER"), (22, 32, "DELIVERY")]}),
    ("Trent Boult delivered a full toss", {"entities": [(0, 11, "BOWLER"), (21, 30, "DELIVERY")]}),
    ("Pat Cummins bowled a short ball", {"entities": [(0, 11, "BOWLER"), (22, 32, "DELIVERY")]}),
    ("Bhuvneshwar Kumar bowled a knuckleball", {"entities": [(0, 17, "BOWLER"), (25, 36, "DELIVERY")]}),
    ("Kagiso Rabada bowled a cutter", {"entities": [(0, 12, "BOWLER"), (20, 26, "DELIVERY")]}),
    ("Anrich Nortje bowled a back-of-the-hand slower ball", {"entities": [(0, 12, "BOWLER"), (20, 52, "DELIVERY")]}),
    ("Chris Morris bowled an inswinger", {"entities": [(0, 11, "BOWLER"), (21, 31, "DELIVERY")]}),
    ("Lungi Ngidi bowled an outswinger", {"entities": [(0, 11, "BOWLER"), (21, 32, "DELIVERY")]}),
    ("Imran Tahir bowled a leg break", {"entities": [(0, 11, "BOWLER"), (21, 30, "DELIVERY")]}),
    ("Yuzvendra Chahal bowled a googly", {"entities": [(0, 16, "BOWLER"), (24, 30, "DELIVERY")]}),
    ("Kuldeep Yadav bowled a chinaman", {"entities": [(0, 13, "BOWLER"), (21, 30, "DELIVERY")]}),
    ("Adil Rashid bowled a flipper", {"entities": [(0, 11, "BOWLER"), (20, 27, "DELIVERY")]}),
    ("Rashid Khan bowled a carrom ball", {"entities": [(0, 11, "BOWLER"), (21, 32, "DELIVERY")]}),
    ("Shakib Al Hasan bowled a slider", {"entities": [(0, 15, "BOWLER"), (24, 30, "DELIVERY")]}),
    ("Sunil Narine bowled a carrom ball", {"entities": [(0, 12, "BOWLER"), (22, 33, "DELIVERY")]}),
    ("Mustafizur Rahman bowled a cutter", {"entities": [(0, 17, "BOWLER"), (25, 31, "DELIVERY")]}),
    ("Jofra Archer bowled a knuckleball", {"entities": [(0, 11, "BOWLER"), (21, 32, "DELIVERY")]}),
    ("James Anderson bowled a swing delivery", {"entities": [(0, 15, "BOWLER"), (23, 37, "DELIVERY")]}),
    ("Stuart Broad bowled a length ball", {"entities": [(0, 12, "BOWLER"), (21, 32, "DELIVERY")]}),
    ("Mark Wood bowled a yorker", {"entities": [(0, 9, "BOWLER"), (17, 23, "DELIVERY")]}),
    ("Nathan Lyon bowled an off break", {"entities": [(0, 11, "BOWLER"), (21, 30, "DELIVERY")]}),
    ("Josh Hazlewood bowled a short ball", {"entities": [(0, 14, "BOWLER"), (23, 32, "DELIVERY")]}),
    ("Pat Cummins bowled a back of a length delivery", {"entities": [(0, 11, "BOWLER"), (21, 47, "DELIVERY")]}),
    ("Mitchell Johnson bowled a bouncer", {"entities": [(0, 16, "BOWLER"), (24, 31, "DELIVERY")]}),
    ("Glenn McGrath bowled a length ball", {"entities": [(0, 12, "BOWLER"), (21, 32, "DELIVERY")]}),
    ("Shane Warne bowled a leg break", {"entities": [(0, 11, "BOWLER"), (21, 30, "DELIVERY")]}),
    ("Muttiah Muralitharan bowled a doosra", {"entities": [(0, 21, "BOWLER"), (29, 35, "DELIVERY")]}),
    ("Lasith Malinga bowled a slower ball", {"entities": [(0, 14, "BOWLER"), (22, 32, "DELIVERY")]}),
    ("Dale Steyn bowled a cutter", {"entities": [(0, 10, "BOWLER"), (18, 24, "DELIVERY")]}),
    ("Shaun Pollock bowled a length ball", {"entities": [(0, 13, "BOWLER"), (22, 33, "DELIVERY")]}),
    ("Allan Donald bowled a bouncer", {"entities": [(0, 12, "BOWLER"), (20, 27, "DELIVERY")]}),
    ("Courtney Walsh bowled a yorker", {"entities": [(0, 14, "BOWLER"), (22, 28, "DELIVERY")]}),
    ("Curtly Ambrose bowled a short ball", {"entities": [(0, 13, "BOWLER"), (22, 32, "DELIVERY")]}),
    ("Wasim Akram bowled a reverse swing delivery", {"entities": [(0, 11, "BOWLER"), (21, 42, "DELIVERY")]}),
    ("Waqar Younis bowled a toe-crusher", {"entities": [(0, 12, "BOWLER"), (21, 32, "DELIVERY")]}),
    ("Anil Kumble bowled a flipper", {"entities": [(0, 11, "BOWLER"), (20, 27, "DELIVERY")]}),
    ("Shoaib Akhtar bowled at lightning speed", {"entities": [(0, 13, "BOWLER"), (21, 37, "DELIVERY")]}),
    ("Saqlain Mushtaq bowled a doosra", {"entities": [(0, 15, "BOWLER"), (23, 29, "DELIVERY")]}),
    ("Harbhajan Singh bowled a doosra", {"entities": [(0, 16, "BOWLER"), (24, 30, "DELIVERY")]}),
    ("Zaheer Khan bowled a yorker", {"entities": [(0, 11, "BOWLER"), (19, 25, "DELIVERY")]}),
    ("Jasprit Bumrah bowled a slower ball", {"entities": [(0, 14, "BOWLER"), (22, 32, "DELIVERY")]}),
    ("Mohammed Shami bowled a good length delivery", {"entities": [(0, 15, "BOWLER"), (23, 45, "DELIVERY")]}),
    ("Ishant Sharma bowled a cutter", {"entities": [(0, 12, "BOWLER"), (20, 26, "DELIVERY")]}),
    ("Umesh Yadav bowled a sharp bouncer", {"entities": [(0, 11, "BOWLER"), (20, 33, "DELIVERY")]}),
    ("Navdeep Saini bowled a short ball", {"entities": [(0, 13, "BOWLER"), (22, 32, "DELIVERY")]}),
    ("Bhuvneshwar Kumar bowled the last over", {"entities": [(0, 17, "BOWLER")]}),
    ("Deepak Chahar bowled accurately", {"entities": [(0, 13, "BOWLER")]}),
    ("T Natarajan bowled the perfect yorker", {"entities": [(0, 11, "BOWLER")]}),

    # Examples for DISMISSAL
    ("Rohit Sharma was caught by the fielder", {"entities": [(0, 12, "BATSMAN"), (16, 22, "DISMISSAL")]}),
    ("Virat Kohli was bowled out", {"entities": [(0, 11, "BATSMAN"), (15, 22, "DISMISSAL")]}),
    ("MS Dhoni was run out", {"entities": [(0, 7, "BATSMAN"), (11, 18, "DISMISSAL")]}),
    ("David Warner was lbw", {"entities": [(0, 12, "BATSMAN"), (16, 19, "DISMISSAL")]}),
    ("Joe Root was stumped", {"entities": [(0, 8, "BATSMAN"), (12, 19, "DISMISSAL")]}),
    ("Steven Smith was caught behind", {"entities": [(0, 12, "BATSMAN"), (16, 30, "DISMISSAL")]}),
    ("Kane Williamson was hit wicket", {"entities": [(0, 15, "BATSMAN"), (19, 29, "DISMISSAL")]}),
    ("Chris Gayle was out lbw", {"entities": [(0, 11, "BATSMAN"), (15, 18, "DISMISSAL")]}),
    ("Babar Azam was caught", {"entities": [(0, 10, "BATSMAN"), (14, 20, "DISMISSAL")]}),
    ("Faf du Plessis was bowled", {"entities": [(0, 13, "BATSMAN"), (17, 24, "DISMISSAL")]}),
    ("Quinton de Kock was run out", {"entities": [(0, 15, "BATSMAN"), (19, 26, "DISMISSAL")]}),
    ("Shikhar Dhawan was caught and bowled", {"entities": [(0, 14, "BATSMAN"), (18, 34, "DISMISSAL")]}),
    ("Ajinkya Rahane was lbw", {"entities": [(0, 13, "BATSMAN"), (17, 20, "DISMISSAL")]}),
    ("Rishabh Pant was out", {"entities": [(0, 11, "BATSMAN"), (15, 18, "DISMISSAL")]}),
    ("KL Rahul was bowled out", {"entities": [(0, 7, "BATSMAN"), (11, 22, "DISMISSAL")]}),
    ("Shreyas Iyer was caught", {"entities": [(0, 12, "BATSMAN"), (16, 22, "DISMISSAL")]}),
    ("Dinesh Karthik was out", {"entities": [(0, 14, "BATSMAN"), (18, 21, "DISMISSAL")]}),
    ("Hardik Pandya was caught behind", {"entities": [(0, 12, "BATSMAN"), (16, 30, "DISMISSAL")]}),
    ("Suryakumar Yadav was lbw", {"entities": [(0, 15, "BATSMAN"), (19, 22, "DISMISSAL")]}),
    ("Prithvi Shaw was caught", {"entities": [(0, 11, "BATSMAN"), (15, 21, "DISMISSAL")]}),
    ("Shubman Gill was bowled out", {"entities": [(0, 11, "BATSMAN"), (15, 26, "DISMISSAL")]}),
    ("Manish Pandey was stumped", {"entities": [(0, 12, "BATSMAN"), (16, 23, "DISMISSAL")]}),
    ("Sanju Samson was caught", {"entities": [(0, 11, "BATSMAN"), (15, 21, "DISMISSAL")]}),
    ("Mayank Agarwal was bowled out", {"entities": [(0, 14, "BATSMAN"), (18, 29, "DISMISSAL")]}),
    ("Kedar Jadhav was caught", {"entities": [(0, 11, "BATSMAN"), (15, 21, "DISMISSAL")]}),
    ("Ishan Kishan was lbw", {"entities": [(0, 11, "BATSMAN"), (15, 18, "DISMISSAL")]}),
    ("Ambati Rayudu was run out", {"entities": [(0, 12, "BATSMAN"), (16, 23, "DISMISSAL")]}),
    ("Ravindra Jadeja was caught", {"entities": [(0, 15, "BATSMAN"), (19, 25, "DISMISSAL")]}),
    ("Axar Patel was bowled", {"entities": [(0, 10, "BATSMAN"), (14, 20, "DISMISSAL")]}),
    ("Ravichandran Ashwin was stumped", {"entities": [(0, 20, "BATSMAN"), (24, 31, "DISMISSAL")]}),
    ("Shardul Thakur was run out", {"entities": [(0, 13, "BATSMAN"), (17, 24, "DISMISSAL")]}),
    ("Washington Sundar was caught behind", {"entities": [(0, 18, "BATSMAN"), (22, 36, "DISMISSAL")]}),
    ("Harbhajan Singh was bowled", {"entities": [(0, 16, "BATSMAN"), (20, 27, "DISMISSAL")]}),
    ("Yuzvendra Chahal was lbw", {"entities": [(0, 16, "BATSMAN"), (20, 23, "DISMISSAL")]}),
    ("Kuldeep Yadav was run out", {"entities": [(0, 13, "BATSMAN"), (17, 24, "DISMISSAL")]}),
    ("Jasprit Bumrah was bowled out", {"entities": [(0, 14, "BATSMAN"), (18, 29, "DISMISSAL")]}),
    ("Mohammed Shami was caught", {"entities": [(0, 15, "BATSMAN"), (19, 25, "DISMISSAL")]}),
    ("Umesh Yadav was lbw", {"entities": [(0, 11, "BATSMAN"), (15, 18, "DISMISSAL")]}),
    ("Bhuvneshwar Kumar was run out", {"entities": [(0, 17, "BATSMAN"), (21, 28, "DISMISSAL")]}),
    ("Navdeep Saini was stumped", {"entities": [(0, 13, "BATSMAN"), (17, 24, "DISMISSAL")]}),
    ("Deepak Chahar was caught behind", {"entities": [(0, 13, "BATSMAN"), (17, 31, "DISMISSAL")]}),
    ("T Natarajan was bowled", {"entities": [(0, 11, "BATSMAN"), (15, 21, "DISMISSAL")]}),
    ("Shane Watson was caught", {"entities": [(0, 12, "BATSMAN"), (16, 22, "DISMISSAL")]}),
    ("Sam Curran was bowled out", {"entities": [(0, 9, "BATSMAN"), (13, 24, "DISMISSAL")]}),
    ("Tom Banton was run out", {"entities": [(0, 10, "BATSMAN"), (14, 21, "DISMISSAL")]}),
    ("Jason Roy was stumped", {"entities": [(0, 9, "BATSMAN"), (13, 20, "DISMISSAL")]}),
    ("Eoin Morgan was caught behind", {"entities": [(0, 11, "BATSMAN"), (15, 29, "DISMISSAL")]}),
    ("Jos Buttler was bowled", {"entities": [(0, 10, "BATSMAN"), (14, 20, "DISMISSAL")]}),
    ("Ben Stokes was run out", {"entities": [(0, 9, "BATSMAN"), (13, 20, "DISMISSAL")]}),
    ("Jonny Bairstow was lbw", {"entities": [(0, 13, "BATSMAN"), (17, 20, "DISMISSAL")]}),
    ("Moeen Ali was stumped", {"entities": [(0, 8, "BATSMAN"), (12, 19, "DISMISSAL")]}),
]
